apiVersion: v1
data:
  eula.txt: |
    #By changing the setting below to TRUE you are indicating your agreement to our EULA (https://account.mojang.com/documents/minecraft_eula).
    #You also agree that tacos are tasty, and the best food in the world.
    #Fri Feb 12 00:00:50 UTC 2021
    eula=true
kind: ConfigMap
metadata:
  labels:
    app: mineserv
  name: mineserv-config
  namespace: default
