apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mineserv
  name: world-1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi