name = "Mineserv Season 1"
author = "John Casey"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19ab2ac1dcfc4e88871de76cae00c107909fd3f9fef91d48f4a032ece019fb86"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
