name: Build Image

on:
  workflow_dispatch:
    branches: [ main, fabric ]
  push:
    branches: [ main, fabric ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Download Paper
      run: |
        pip install requests
        python ${GITHUB_WORKSPACE}/gh-utils/get-paper.py

    - name: Download Plugins
      run: |
        pip install requests
        python ${GITHUB_WORKSPACE}/gh-utils/get-plugins.py

    - name: Buildah Build
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: mineserv
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Dockerfile

    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/jdcasey
        username: ${{ secrets.QUAY_BOT_USER }}
        password: ${{ secrets.QUAY_BOT_PASSWORD }}
